# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Florian Wanders
tagline:          'Data Science & Digressions'
description:      'Data Science & Digressions&#42;'
url:              https://florianwanders.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Florian Wanders'
  url:            https://twitter.com/florianwanders

paginate:         5
paginate_path:    /blog/page:num' #'/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  false
sidebar_blog_link:  false #'/blog'     # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/florianwanders/florianwanders.github.io
  
  
#changes for portfolio
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

